openapi: 3.0.0
components:
  schemas:
    URL:
      example: (ftp|http(s)|mail...)://google.com
      type: string
      format: uri
      x-go-type: github.com/mikekonan/go-types/v2/url.URL
    HttpURL:
      example: http(s)://google.com
      type: string
      format: uri
      x-go-type: github.com/mikekonan/go-types/v2/url.HttpURL
    NullHttpURL:
      example: http(s)://google.com
      type: string
      format: uri
      x-go-type: github.com/mikekonan/go-types/v2/url.NullHttpURL
