language: go

go:
  - 1.19.x

before_script:
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0

script:
  - make fmt lint test

after_success:
  - bash <(curl -s https://codecov.io/bash)
