openapi: 3.0.0
components:
  schemas:
    CardDate:
      example: 01/06
      type: string
      x-go-type: github.com/mikekonan/go-types/v2/card.CardDate
    Email:
      example: user@example.com
      type: string
      format: email
      x-go-type: github.com/mikekonan/go-types/v2/email.Email
    IPv4:
      example: 1.1.1.1
      type: string
      format: IPv4
      x-go-type: github.com/mikekonan/go-types/v2/ip.IPv4
    LanguageName:
      example: Norwegian
      type: string
      format: string
      enum:
        - Afar
        - Abkhazian
        - Afrikaans
        - Akan
        - Albanian
        - Amharic
        - Arabic
        - Aragonese
        - Armenian
        - Assamese
        - Avaric
        - Avestan
        - Aymara
        - Azerbaijani
        - Bashkir
        - Bambara
        - Basque
        - Belarusian
        - Bengali
        - Bihari languages
        - Bislama
        - Bosnian
        - Breton
        - Bulgarian
        - Burmese
        - Catalan
        - Chamorro
        - Chechen
        - Chinese
        - Church Slavic
        - Chuvash
        - Cornish
        - Corsican
        - Cree
        - Czech
        - Danish
        - Divehi
        - Dutch
        - Dzongkha
        - English
        - Esperanto
        - Estonian
        - Ewe
        - Faroese
        - Fijian
        - Finnish
        - French
        - Western Frisian
        - Fulah
        - Georgian
        - German
        - Gaelic
        - Irish
        - Galician
        - Manx
        - Greek Modern
        - Guarani
        - Gujarati
        - Haitian
        - Hausa
        - Hebrew
        - Herero
        - Hindi
        - Hiri Motu
        - Croatian
        - Hungarian
        - Igbo
        - Icelandic
        - Ido
        - Sichuan Yi
        - Inuktitut
        - Interlingue
        - Interlingua
        - Indonesian
        - Inupiaq
        - Italian
        - Javanese
        - Japanese
        - Kalaallisut
        - Kannada
        - Kashmiri
        - Kanuri
        - Kazakh
        - Central Khmer
        - Kikuyu
        - Kinyarwanda
        - Kirghiz
        - Komi
        - Kongo
        - Korean
        - Kuanyama
        - Kurdish
        - Lao
        - Latin
        - Latvian
        - Limburgan
        - Lingala
        - Lithuanian
        - Luxembourgish
        - Luba-Katanga
        - Ganda
        - Macedonian
        - Marshallese
        - Malayalam
        - Maori
        - Marathi
        - Malay
        - Malagasy
        - Maltese
        - Mongolian
        - Nauru
        - Navajo
        - Ndebele South
        - Ndebele North
        - Ndonga
        - Nepali
        - Norwegian Nynorsk
        - Bokmål Norwegian
        - Norwegian
        - Chichewa
        - Occitan
        - Ojibwa
        - Oriya
        - Oromo
        - Ossetian
        - Panjabi
        - Persian
        - Pali
        - Polish
        - Portuguese
        - Pushto
        - Quechua
        - Romansh
        - Romanian
        - Rundi
        - Russian
        - Sango
        - Sanskrit
        - Sinhala
        - Slovak
        - Slovenian
        - Northern Sami
        - Samoan
        - Shona
        - Sindhi
        - Somali
        - Sotho Southern
        - Spanish
        - Sardinian
        - Serbian
        - Swati
        - Sundanese
        - Swahili
        - Swedish
        - Tahitian
        - Tamil
        - Tatar
        - Telugu
        - Tajik
        - Tagalog
        - Thai
        - Tibetan
        - Tigrinya
        - Tonga
        - Tswana
        - Tsonga
        - Turkmen
        - Turkish
        - Twi
        - Uighur
        - Ukrainian
        - Urdu
        - Uzbek
        - Venda
        - Vietnamese
        - Volapük
        - Welsh
        - Walloon
        - Wolof
        - Xhosa
        - Yiddish
        - Yoruba
        - Zhuang
        - Zulu
      x-go-type: github.com/mikekonan/go-types/v2/language.Name
    CountryAlpha2:
      example: no
      type: string
      format: ISO 639-1
      minLength: 2
      maxLength: 2
      enum:
        - aa
        - ab
        - af
        - ak
        - sq
        - am
        - ar
        - an
        - hy
        - as
        - av
        - ae
        - ay
        - az
        - ba
        - bm
        - eu
        - be
        - bn
        - bh
        - bi
        - bs
        - br
        - bg
        - my
        - ca
        - ch
        - ce
        - zh
        - cu
        - cv
        - kw
        - co
        - cr
        - cs
        - da
        - dv
        - nl
        - dz
        - en
        - eo
        - et
        - ee
        - fo
        - fj
        - fi
        - fr
        - fy
        - ff
        - ka
        - de
        - gd
        - ga
        - gl
        - gv
        - el
        - gn
        - gu
        - ht
        - ha
        - he
        - hz
        - hi
        - ho
        - hr
        - hu
        - ig
        - is
        - io
        - ii
        - iu
        - ie
        - ia
        - id
        - ik
        - it
        - jv
        - ja
        - kl
        - kn
        - ks
        - kr
        - kk
        - km
        - ki
        - rw
        - ky
        - kv
        - kg
        - ko
        - kj
        - ku
        - lo
        - la
        - lv
        - li
        - ln
        - lt
        - lb
        - lu
        - lg
        - mk
        - mh
        - ml
        - mi
        - mr
        - ms
        - mg
        - mt
        - mn
        - na
        - nv
        - nr
        - nd
        - ng
        - ne
        - nn
        - nb
        - no
        - ny
        - oc
        - oj
        - or
        - om
        - os
        - pa
        - fa
        - pi
        - pl
        - pt
        - ps
        - qu
        - rm
        - ro
        - rn
        - ru
        - sg
        - sa
        - si
        - sk
        - sl
        - se
        - sm
        - sn
        - sd
        - so
        - st
        - es
        - sc
        - sr
        - ss
        - su
        - sw
        - sv
        - ty
        - ta
        - tt
        - te
        - tg
        - tl
        - th
        - bo
        - ti
        - to
        - tn
        - ts
        - tk
        - tr
        - tw
        - ug
        - uk
        - ur
        - uz
        - ve
        - vi
        - vo
        - cy
        - wa
        - wo
        - xh
        - yi
        - yo
        - za
        - zu
      x-go-type: github.com/mikekonan/go-types/v2/language.Alpha2Code
    CountryAlpha3:
      example: nor
      type: string
      format: ISO 639-1
      minLength: 3
      maxLength: 3
      enum:
        - aar
        - abk
        - afr
        - aka
        - alb
        - amh
        - ara
        - arg
        - arm
        - asm
        - ava
        - ave
        - aym
        - aze
        - bak
        - bam
        - baq
        - bel
        - ben
        - bih
        - bis
        - bos
        - bre
        - bul
        - bur
        - cat
        - cha
        - che
        - chi
        - chu
        - chv
        - cor
        - cos
        - cre
        - cze
        - dan
        - div
        - dut
        - dzo
        - eng
        - epo
        - est
        - ewe
        - fao
        - fij
        - fin
        - fre
        - fry
        - ful
        - geo
        - ger
        - gla
        - gle
        - glg
        - glv
        - gre
        - grn
        - guj
        - hat
        - hau
        - heb
        - her
        - hin
        - hmo
        - hrv
        - hun
        - ibo
        - ice
        - ido
        - iii
        - iku
        - ile
        - ina
        - ind
        - ipk
        - ita
        - jav
        - jpn
        - kal
        - kan
        - kas
        - kau
        - kaz
        - khm
        - kik
        - kin
        - kir
        - kom
        - kon
        - kor
        - kua
        - kur
        - lao
        - lat
        - lav
        - lim
        - lin
        - lit
        - ltz
        - lub
        - lug
        - mac
        - mah
        - mal
        - mao
        - mar
        - may
        - mlg
        - mlt
        - mon
        - nau
        - nav
        - nbl
        - nde
        - ndo
        - nep
        - nno
        - nob
        - nor
        - nya
        - oci
        - oji
        - ori
        - orm
        - oss
        - pan
        - per
        - pli
        - pol
        - por
        - pus
        - que
        - roh
        - rum
        - run
        - rus
        - sag
        - san
        - sin
        - slo
        - slv
        - sme
        - smo
        - sna
        - snd
        - som
        - sot
        - spa
        - srd
        - srp
        - ssw
        - sun
        - swa
        - swe
        - tah
        - tam
        - tat
        - tel
        - tgk
        - tgl
        - tha
        - tib
        - tir
        - ton
        - tsn
        - tso
        - tuk
        - tur
        - twi
        - uig
        - ukr
        - urd
        - uzb
        - ven
        - vie
        - vol
        - wel
        - wln
        - wol
        - xho
        - yid
        - yor
        - zha
        - zul
      x-go-type: github.com/mikekonan/go-types/v2/language.Alpha3Code
    DialCountryCode:
      example: 1-829
      type: string
      format: E.164
      enum:
        - "1"
        - "7"
        - "20"
        - "27"
        - "30"
        - "31"
        - "32"
        - "33"
        - "34"
        - "36"
        - "39"
        - "40"
        - "41"
        - "43"
        - "44"
        - "45"
        - "46"
        - "47"
        - "48"
        - "49"
        - "51"
        - "52"
        - "53"
        - "54"
        - "55"
        - "56"
        - "57"
        - "58"
        - "60"
        - "61"
        - "62"
        - "63"
        - "64"
        - "65"
        - "66"
        - "81"
        - "82"
        - "84"
        - "86"
        - "90"
        - "91"
        - "92"
        - "93"
        - "94"
        - "95"
        - "98"
        - "211"
        - "212"
        - "213"
        - "216"
        - "218"
        - "220"
        - "221"
        - "222"
        - "223"
        - "224"
        - "225"
        - "226"
        - "227"
        - "228"
        - "229"
        - "230"
        - "231"
        - "232"
        - "233"
        - "234"
        - "235"
        - "236"
        - "237"
        - "238"
        - "239"
        - "240"
        - "241"
        - "242"
        - "243"
        - "244"
        - "245"
        - "246"
        - "248"
        - "249"
        - "250"
        - "251"
        - "252"
        - "253"
        - "254"
        - "255"
        - "256"
        - "257"
        - "258"
        - "260"
        - "261"
        - "262"
        - "263"
        - "264"
        - "265"
        - "266"
        - "267"
        - "268"
        - "269"
        - "290"
        - "291"
        - "297"
        - "298"
        - "299"
        - "350"
        - "351"
        - "352"
        - "353"
        - "354"
        - "355"
        - "356"
        - "357"
        - "358"
        - "359"
        - "370"
        - "371"
        - "372"
        - "373"
        - "374"
        - "375"
        - "376"
        - "377"
        - "378"
        - "380"
        - "381"
        - "382"
        - "385"
        - "386"
        - "387"
        - "389"
        - "420"
        - "421"
        - "423"
        - "500"
        - "501"
        - "502"
        - "503"
        - "504"
        - "505"
        - "506"
        - "507"
        - "508"
        - "509"
        - "590"
        - "591"
        - "592"
        - "593"
        - "594"
        - "595"
        - "596"
        - "597"
        - "598"
        - "599"
        - "670"
        - "672"
        - "673"
        - "674"
        - "675"
        - "676"
        - "677"
        - "678"
        - "679"
        - "680"
        - "681"
        - "682"
        - "683"
        - "685"
        - "686"
        - "687"
        - "688"
        - "689"
        - "690"
        - "691"
        - "692"
        - "850"
        - "852"
        - "853"
        - "855"
        - "856"
        - "870"
        - "880"
        - "886"
        - "960"
        - "961"
        - "962"
        - "963"
        - "964"
        - "965"
        - "966"
        - "967"
        - "968"
        - "970"
        - "971"
        - "972"
        - "973"
        - "974"
        - "975"
        - "976"
        - "977"
        - "992"
        - "993"
        - "994"
        - "995"
        - "996"
        - "998"
        - 1-684
        - 1-264
        - 1-268
        - 1-242
        - 1-246
        - 1-441
        - 1-284
        - 1-345
        - 1-767
        - 1-809
        - 1-829
        - 1-849
        - 1-473
        - 1-671
        - 39-06
        - 1-876
        - 1-664
        - 1-670
        - 1-869
        - 1-758
        - 1-784
        - 1-721
        - 1-868
        - 1-649
        - 1-340
      x-go-type: github.com/mikekonan/go-types/v2/phone.DialCode
    PostalCode:
      example: CA6633
      type: string
      x-go-type: github.com/mikekonan/go-types/v2/postalcode.PostalCode
    Date:
      example: 2006-01-02
      type: string
      x-go-type: github.com/mikekonan/go-types/v2/time.Date
      x-go-type-string-parse: github.com/mikekonan/go-types/v2/time.ParseDateFromString
    NullTime:
      example: 2020-12-08T16:38:09.70516Z
      type: string
      nullable: true
      x-go-type: github.com/mikekonan/go-types/v2/time.Time
      x-go-type-string-parse: github.com/mikekonan/go-types/v2/time.ParseNullTimeFromString
    URL:
      example: (ftp|http(s)|mail...)://google.com
      type: string
      format: uri
      x-go-type: github.com/mikekonan/go-types/v2/url.URL
    HttpURL:
      example: http(s)://google.com
      type: string
      format: uri
      x-go-type: github.com/mikekonan/go-types/v2/url.HttpURL
    NullHttpURL:
      example: http(s)://google.com
      type: string
      format: uri
      x-go-type: github.com/mikekonan/go-types/v2/url.NullHttpURL
