openapi: 3.0.0
components:
  schemas:
    Date:
      example: 2006-01-02
      type: string
      x-go-type: github.com/mikekonan/go-types/v2/time.Date
      x-go-type-string-parse: github.com/mikekonan/go-types/v2/time.ParseDateFromString
    NullTime:
      example: 2020-12-08T16:38:09.70516Z
      type: string
      nullable: true
      x-go-type: github.com/mikekonan/go-types/v2/time.Time
      x-go-type-string-parse: github.com/mikekonan/go-types/v2/time.ParseNullTimeFromString
