package country

var CountryByName = map[string]Country{
	"Aruba" : Aruba,
	"Afghanistan" : Afghanistan,
	"Angola" : Angola,
	"Anguilla" : Anguilla,
	"Åland Islands" : AlandIslands,
	"Albania" : Albania,
	"Andorra" : Andorra,
	"United Arab Emirates" : UnitedArabEmirates,
	"Argentina" : Argentina,
	"Armenia" : Armenia,
	"American Samoa" : AmericanSamoa,
	"Antarctica" : Antarctica,
	"French Southern Territories" : FrenchSouthern,
	"Antigua and Barbuda" : AntiguaAndBarbuda,
	"Australia" : Australia,
	"Austria" : Austria,
	"Azerbaijan" : Azerbaijan,
	"Burundi" : Burundi,
	"Belgium" : Belgium,
	"Benin" : Benin,
	"Bonaire, Sint Eustatius and Saba" : Bonaire,
	"Burkina Faso" : BurkinaFaso,
	"Bangladesh" : Bangladesh,
	"Bulgaria" : Bulgaria,
	"Bahrain" : Bahrain,
	"Bahamas" : Bahamas,
	"Bosnia and Herzegovina" : BosniaAndHerzegovina,
	"Saint Barthélemy" : SaintBarthelemy,
	"Belarus" : Belarus,
	"Belize" : Belize,
	"Bermuda" : Bermuda,
	"Bolivia, Plurinational State of" : Bolivia,
	"Brazil" : Brazil,
	"Barbados" : Barbados,
	"Brunei Darussalam" : BruneiDarussalam,
	"Bhutan" : Bhutan,
	"Bouvet Island" : BouvetIsland,
	"Botswana" : Botswana,
	"Central African Republic" : CentralAfricanRepublic,
	"Canada" : Canada,
	"Cocos (Keeling) Islands" : CocosIslands,
	"Switzerland" : Switzerland,
	"Chile" : Chile,
	"China" : China,
	"Côte d'Ivoire" : CoteDIvoire,
	"Cameroon" : Cameroon,
	"Congo, The Democratic Republic of the" : DRCongo,
	"Congo" : Congo,
	"Cook Islands" : CookIslands,
	"Colombia" : Colombia,
	"Comoros" : Comoros,
	"Cabo Verde" : CaboVerde,
	"Costa Rica" : CostaRica,
	"Cuba" : Cuba,
	"Curaçao" : Curacao,
	"Christmas Island" : ChristmasIsland,
	"Cayman Islands" : CaymanIslands,
	"Cyprus" : Cyprus,
	"Czechia" : Czechia,
	"Germany" : Germany,
	"Djibouti" : Djibouti,
	"Dominica" : Dominica,
	"Denmark" : Denmark,
	"Dominican Republic" : DominicanRepublic,
	"Algeria" : Algeria,
	"Ecuador" : Ecuador,
	"Egypt" : Egypt,
	"Eritrea" : Eritrea,
	"Western Sahara" : WesternSahara,
	"Spain" : Spain,
	"Estonia" : Estonia,
	"Ethiopia" : Ethiopia,
	"Finland" : Finland,
	"Fiji" : Fiji,
	"Falkland Islands (Malvinas)" : FalklandIslands,
	"France" : France,
	"Faroe Islands" : FaroeIslands,
	"Micronesia, Federated States of" : Micronesia,
	"Gabon" : Gabon,
	"United Kingdom" : UnitedKingdom,
	"Georgia" : Georgia,
	"Guernsey" : Guernsey,
	"Ghana" : Ghana,
	"Gibraltar" : Gibraltar,
	"Guinea" : Guinea,
	"Guadeloupe" : Guadeloupe,
	"Gambia" : Gambia,
	"Guinea-Bissau" : GuineaBissau,
	"Equatorial Guinea" : EquatorialGuinea,
	"Greece" : Greece,
	"Grenada" : Grenada,
	"Greenland" : Greenland,
	"Guatemala" : Guatemala,
	"French Guiana" : FrenchGuiana,
	"Guam" : Guam,
	"Guyana" : Guyana,
	"Hong Kong" : HongKong,
	"Heard Island and McDonald Islands" : HeardIsland,
	"Honduras" : Honduras,
	"Croatia" : Croatia,
	"Haiti" : Haiti,
	"Hungary" : Hungary,
	"Indonesia" : Indonesia,
	"Isle of Man" : IsleOfMan,
	"India" : India,
	"British Indian Ocean Territory" : BritishIndianOcean,
	"Ireland" : Ireland,
	"Iran, Islamic Republic of" : Iran,
	"Iraq" : Iraq,
	"Iceland" : Iceland,
	"Israel" : Israel,
	"Italy" : Italy,
	"Jamaica" : Jamaica,
	"Jersey" : Jersey,
	"Jordan" : Jordan,
	"Japan" : Japan,
	"Kazakhstan" : Kazakhstan,
	"Kenya" : Kenya,
	"Kyrgyzstan" : Kyrgyzstan,
	"Cambodia" : Cambodia,
	"Kiribati" : Kiribati,
	"Saint Kitts and Nevis" : SaintKittsAndNevis,
	"Korea, Republic of" : SouthKorea,
	"Kuwait" : Kuwait,
	"Lao People's Democratic Republic" : Laos,
	"Lebanon" : Lebanon,
	"Liberia" : Liberia,
	"Libya" : Libya,
	"Saint Lucia" : SaintLucia,
	"Liechtenstein" : Liechtenstein,
	"Sri Lanka" : SriLanka,
	"Lesotho" : Lesotho,
	"Lithuania" : Lithuania,
	"Luxembourg" : Luxembourg,
	"Latvia" : Latvia,
	"Macao" : Macao,
	"Saint Martin (French part)" : SaintMartin,
	"Morocco" : Morocco,
	"Monaco" : Monaco,
	"Moldova, Republic of" : Moldova,
	"Madagascar" : Madagascar,
	"Maldives" : Maldives,
	"Mexico" : Mexico,
	"Marshall Islands" : MarshallIslands,
	"North Macedonia" : NorthMacedonia,
	"Mali" : Mali,
	"Malta" : Malta,
	"Myanmar" : Myanmar,
	"Montenegro" : Montenegro,
	"Mongolia" : Mongolia,
	"Northern Mariana Islands" : NorthernMarianaIslands,
	"Mozambique" : Mozambique,
	"Mauritania" : Mauritania,
	"Montserrat" : Montserrat,
	"Martinique" : Martinique,
	"Mauritius" : Mauritius,
	"Malawi" : Malawi,
	"Malaysia" : Malaysia,
	"Mayotte" : Mayotte,
	"Namibia" : Namibia,
	"New Caledonia" : NewCaledonia,
	"Niger" : Niger,
	"Norfolk Island" : NorfolkIsland,
	"Nigeria" : Nigeria,
	"Nicaragua" : Nicaragua,
	"Niue" : Niue,
	"Netherlands" : Netherlands,
	"Norway" : Norway,
	"Nepal" : Nepal,
	"Nauru" : Nauru,
	"New Zealand" : NewZealand,
	"Oman" : Oman,
	"Pakistan" : Pakistan,
	"Panama" : Panama,
	"Pitcairn" : Pitcairn,
	"Peru" : Peru,
	"Philippines" : Philippines,
	"Palau" : Palau,
	"Papua New Guinea" : PapuaNewGuinea,
	"Poland" : Poland,
	"Puerto Rico" : PuertoRico,
	"Korea, Democratic People's Republic of" : NorthKorea,
	"Portugal" : Portugal,
	"Paraguay" : Paraguay,
	"Palestine, State of" : Palestine,
	"French Polynesia" : FrenchPolynesia,
	"Qatar" : Qatar,
	"Réunion" : Reunion,
	"Romania" : Romania,
	"Russian Federation" : RussianFederation,
	"Rwanda" : Rwanda,
	"Saudi Arabia" : SaudiArabia,
	"Sudan" : Sudan,
	"Senegal" : Senegal,
	"Singapore" : Singapore,
	"South Georgia and the South Sandwich Islands" : SouthGeorgia,
	"Saint Helena, Ascension and Tristan da Cunha" : SaintHelena,
	"Svalbard and Jan Mayen" : SvalbardAndJanMayen,
	"Solomon Islands" : SolomonIslands,
	"Sierra Leone" : SierraLeone,
	"El Salvador" : ElSalvador,
	"San Marino" : SanMarino,
	"Somalia" : Somalia,
	"Saint Pierre and Miquelon" : SaintPierreAndMiquelon,
	"Serbia" : Serbia,
	"South Sudan" : SouthSudan,
	"Sao Tome and Principe" : SaoTomeAndPrincipe,
	"Suriname" : Suriname,
	"Slovakia" : Slovakia,
	"Slovenia" : Slovenia,
	"Sweden" : Sweden,
	"Eswatini" : Eswatini,
	"Sint Maarten (Dutch part)" : SintMaarten,
	"Seychelles" : Seychelles,
	"Syrian Arab Republic" : Syria,
	"Turks and Caicos Islands" : TurksAndCaicosIslands,
	"Chad" : Chad,
	"Togo" : Togo,
	"Thailand" : Thailand,
	"Tajikistan" : Tajikistan,
	"Tokelau" : Tokelau,
	"Turkmenistan" : Turkmenistan,
	"Timor-Leste" : TimorLeste,
	"Tonga" : Tonga,
	"Trinidad and Tobago" : TrinidadAndTobago,
	"Tunisia" : Tunisia,
	"Türkiye" : Turkiye,
	"Tuvalu" : Tuvalu,
	"Taiwan, Province of China" : Taiwan,
	"Tanzania, United Republic of" : Tanzania,
	"Uganda" : Uganda,
	"Ukraine" : Ukraine,
	"United States Minor Outlying Islands" : USMinorOutlyingIslands,
	"Uruguay" : Uruguay,
	"United States" : UnitedStates,
	"Uzbekistan" : Uzbekistan,
	"Holy See (Vatican City State)" : Vatican,
	"Saint Vincent and the Grenadines" : SaintVincentAndTheGrenadines,
	"Venezuela, Bolivarian Republic of" : Venezuela,
	"Virgin Islands, British" : BritishVirginIslands,
	"Virgin Islands, U.S." : USVirginIslands,
	"Viet Nam" : VietNam,
	"Vanuatu" : Vanuatu,
	"Wallis and Futuna" : WallisAndFutuna,
	"Samoa" : Samoa,
	"Yemen" : Yemen,
	"South Africa" : SouthAfrica,
	"Zambia" : Zambia,
	"Zimbabwe" : Zimbabwe,
}

var CountryByAlpha2 = map[string]Country{
	"AW" : Aruba,
	"AF" : Afghanistan,
	"AO" : Angola,
	"AI" : Anguilla,
	"AX" : AlandIslands,
	"AL" : Albania,
	"AD" : Andorra,
	"AE" : UnitedArabEmirates,
	"AR" : Argentina,
	"AM" : Armenia,
	"AS" : AmericanSamoa,
	"AQ" : Antarctica,
	"TF" : FrenchSouthern,
	"AG" : AntiguaAndBarbuda,
	"AU" : Australia,
	"AT" : Austria,
	"AZ" : Azerbaijan,
	"BI" : Burundi,
	"BE" : Belgium,
	"BJ" : Benin,
	"BQ" : Bonaire,
	"BF" : BurkinaFaso,
	"BD" : Bangladesh,
	"BG" : Bulgaria,
	"BH" : Bahrain,
	"BS" : Bahamas,
	"BA" : BosniaAndHerzegovina,
	"BL" : SaintBarthelemy,
	"BY" : Belarus,
	"BZ" : Belize,
	"BM" : Bermuda,
	"BO" : Bolivia,
	"BR" : Brazil,
	"BB" : Barbados,
	"BN" : BruneiDarussalam,
	"BT" : Bhutan,
	"BV" : BouvetIsland,
	"BW" : Botswana,
	"CF" : CentralAfricanRepublic,
	"CA" : Canada,
	"CC" : CocosIslands,
	"CH" : Switzerland,
	"CL" : Chile,
	"CN" : China,
	"CI" : CoteDIvoire,
	"CM" : Cameroon,
	"CD" : DRCongo,
	"CG" : Congo,
	"CK" : CookIslands,
	"CO" : Colombia,
	"KM" : Comoros,
	"CV" : CaboVerde,
	"CR" : CostaRica,
	"CU" : Cuba,
	"CW" : Curacao,
	"CX" : ChristmasIsland,
	"KY" : CaymanIslands,
	"CY" : Cyprus,
	"CZ" : Czechia,
	"DE" : Germany,
	"DJ" : Djibouti,
	"DM" : Dominica,
	"DK" : Denmark,
	"DO" : DominicanRepublic,
	"DZ" : Algeria,
	"EC" : Ecuador,
	"EG" : Egypt,
	"ER" : Eritrea,
	"EH" : WesternSahara,
	"ES" : Spain,
	"EE" : Estonia,
	"ET" : Ethiopia,
	"FI" : Finland,
	"FJ" : Fiji,
	"FK" : FalklandIslands,
	"FR" : France,
	"FO" : FaroeIslands,
	"FM" : Micronesia,
	"GA" : Gabon,
	"GB" : UnitedKingdom,
	"GE" : Georgia,
	"GG" : Guernsey,
	"GH" : Ghana,
	"GI" : Gibraltar,
	"GN" : Guinea,
	"GP" : Guadeloupe,
	"GM" : Gambia,
	"GW" : GuineaBissau,
	"GQ" : EquatorialGuinea,
	"GR" : Greece,
	"GD" : Grenada,
	"GL" : Greenland,
	"GT" : Guatemala,
	"GF" : FrenchGuiana,
	"GU" : Guam,
	"GY" : Guyana,
	"HK" : HongKong,
	"HM" : HeardIsland,
	"HN" : Honduras,
	"HR" : Croatia,
	"HT" : Haiti,
	"HU" : Hungary,
	"ID" : Indonesia,
	"IM" : IsleOfMan,
	"IN" : India,
	"IO" : BritishIndianOcean,
	"IE" : Ireland,
	"IR" : Iran,
	"IQ" : Iraq,
	"IS" : Iceland,
	"IL" : Israel,
	"IT" : Italy,
	"JM" : Jamaica,
	"JE" : Jersey,
	"JO" : Jordan,
	"JP" : Japan,
	"KZ" : Kazakhstan,
	"KE" : Kenya,
	"KG" : Kyrgyzstan,
	"KH" : Cambodia,
	"KI" : Kiribati,
	"KN" : SaintKittsAndNevis,
	"KR" : SouthKorea,
	"KW" : Kuwait,
	"LA" : Laos,
	"LB" : Lebanon,
	"LR" : Liberia,
	"LY" : Libya,
	"LC" : SaintLucia,
	"LI" : Liechtenstein,
	"LK" : SriLanka,
	"LS" : Lesotho,
	"LT" : Lithuania,
	"LU" : Luxembourg,
	"LV" : Latvia,
	"MO" : Macao,
	"MF" : SaintMartin,
	"MA" : Morocco,
	"MC" : Monaco,
	"MD" : Moldova,
	"MG" : Madagascar,
	"MV" : Maldives,
	"MX" : Mexico,
	"MH" : MarshallIslands,
	"MK" : NorthMacedonia,
	"ML" : Mali,
	"MT" : Malta,
	"MM" : Myanmar,
	"ME" : Montenegro,
	"MN" : Mongolia,
	"MP" : NorthernMarianaIslands,
	"MZ" : Mozambique,
	"MR" : Mauritania,
	"MS" : Montserrat,
	"MQ" : Martinique,
	"MU" : Mauritius,
	"MW" : Malawi,
	"MY" : Malaysia,
	"YT" : Mayotte,
	"NA" : Namibia,
	"NC" : NewCaledonia,
	"NE" : Niger,
	"NF" : NorfolkIsland,
	"NG" : Nigeria,
	"NI" : Nicaragua,
	"NU" : Niue,
	"NL" : Netherlands,
	"NO" : Norway,
	"NP" : Nepal,
	"NR" : Nauru,
	"NZ" : NewZealand,
	"OM" : Oman,
	"PK" : Pakistan,
	"PA" : Panama,
	"PN" : Pitcairn,
	"PE" : Peru,
	"PH" : Philippines,
	"PW" : Palau,
	"PG" : PapuaNewGuinea,
	"PL" : Poland,
	"PR" : PuertoRico,
	"KP" : NorthKorea,
	"PT" : Portugal,
	"PY" : Paraguay,
	"PS" : Palestine,
	"PF" : FrenchPolynesia,
	"QA" : Qatar,
	"RE" : Reunion,
	"RO" : Romania,
	"RU" : RussianFederation,
	"RW" : Rwanda,
	"SA" : SaudiArabia,
	"SD" : Sudan,
	"SN" : Senegal,
	"SG" : Singapore,
	"GS" : SouthGeorgia,
	"SH" : SaintHelena,
	"SJ" : SvalbardAndJanMayen,
	"SB" : SolomonIslands,
	"SL" : SierraLeone,
	"SV" : ElSalvador,
	"SM" : SanMarino,
	"SO" : Somalia,
	"PM" : SaintPierreAndMiquelon,
	"RS" : Serbia,
	"SS" : SouthSudan,
	"ST" : SaoTomeAndPrincipe,
	"SR" : Suriname,
	"SK" : Slovakia,
	"SI" : Slovenia,
	"SE" : Sweden,
	"SZ" : Eswatini,
	"SX" : SintMaarten,
	"SC" : Seychelles,
	"SY" : Syria,
	"TC" : TurksAndCaicosIslands,
	"TD" : Chad,
	"TG" : Togo,
	"TH" : Thailand,
	"TJ" : Tajikistan,
	"TK" : Tokelau,
	"TM" : Turkmenistan,
	"TL" : TimorLeste,
	"TO" : Tonga,
	"TT" : TrinidadAndTobago,
	"TN" : Tunisia,
	"TR" : Turkiye,
	"TV" : Tuvalu,
	"TW" : Taiwan,
	"TZ" : Tanzania,
	"UG" : Uganda,
	"UA" : Ukraine,
	"UM" : USMinorOutlyingIslands,
	"UY" : Uruguay,
	"US" : UnitedStates,
	"UZ" : Uzbekistan,
	"VA" : Vatican,
	"VC" : SaintVincentAndTheGrenadines,
	"VE" : Venezuela,
	"VG" : BritishVirginIslands,
	"VI" : USVirginIslands,
	"VN" : VietNam,
	"VU" : Vanuatu,
	"WF" : WallisAndFutuna,
	"WS" : Samoa,
	"YE" : Yemen,
	"ZA" : SouthAfrica,
	"ZM" : Zambia,
	"ZW" : Zimbabwe,
}

var CountryByAlpha3 = map[string]Country{
	"ABW" : Aruba,
	"AFG" : Afghanistan,
	"AGO" : Angola,
	"AIA" : Anguilla,
	"ALA" : AlandIslands,
	"ALB" : Albania,
	"AND" : Andorra,
	"ARE" : UnitedArabEmirates,
	"ARG" : Argentina,
	"ARM" : Armenia,
	"ASM" : AmericanSamoa,
	"ATA" : Antarctica,
	"ATF" : FrenchSouthern,
	"ATG" : AntiguaAndBarbuda,
	"AUS" : Australia,
	"AUT" : Austria,
	"AZE" : Azerbaijan,
	"BDI" : Burundi,
	"BEL" : Belgium,
	"BEN" : Benin,
	"BES" : Bonaire,
	"BFA" : BurkinaFaso,
	"BGD" : Bangladesh,
	"BGR" : Bulgaria,
	"BHR" : Bahrain,
	"BHS" : Bahamas,
	"BIH" : BosniaAndHerzegovina,
	"BLM" : SaintBarthelemy,
	"BLR" : Belarus,
	"BLZ" : Belize,
	"BMU" : Bermuda,
	"BOL" : Bolivia,
	"BRA" : Brazil,
	"BRB" : Barbados,
	"BRN" : BruneiDarussalam,
	"BTN" : Bhutan,
	"BVT" : BouvetIsland,
	"BWA" : Botswana,
	"CAF" : CentralAfricanRepublic,
	"CAN" : Canada,
	"CCK" : CocosIslands,
	"CHE" : Switzerland,
	"CHL" : Chile,
	"CHN" : China,
	"CIV" : CoteDIvoire,
	"CMR" : Cameroon,
	"COD" : DRCongo,
	"COG" : Congo,
	"COK" : CookIslands,
	"COL" : Colombia,
	"COM" : Comoros,
	"CPV" : CaboVerde,
	"CRI" : CostaRica,
	"CUB" : Cuba,
	"CUW" : Curacao,
	"CXR" : ChristmasIsland,
	"CYM" : CaymanIslands,
	"CYP" : Cyprus,
	"CZE" : Czechia,
	"DEU" : Germany,
	"DJI" : Djibouti,
	"DMA" : Dominica,
	"DNK" : Denmark,
	"DOM" : DominicanRepublic,
	"DZA" : Algeria,
	"ECU" : Ecuador,
	"EGY" : Egypt,
	"ERI" : Eritrea,
	"ESH" : WesternSahara,
	"ESP" : Spain,
	"EST" : Estonia,
	"ETH" : Ethiopia,
	"FIN" : Finland,
	"FJI" : Fiji,
	"FLK" : FalklandIslands,
	"FRA" : France,
	"FRO" : FaroeIslands,
	"FSM" : Micronesia,
	"GAB" : Gabon,
	"GBR" : UnitedKingdom,
	"GEO" : Georgia,
	"GGY" : Guernsey,
	"GHA" : Ghana,
	"GIB" : Gibraltar,
	"GIN" : Guinea,
	"GLP" : Guadeloupe,
	"GMB" : Gambia,
	"GNB" : GuineaBissau,
	"GNQ" : EquatorialGuinea,
	"GRC" : Greece,
	"GRD" : Grenada,
	"GRL" : Greenland,
	"GTM" : Guatemala,
	"GUF" : FrenchGuiana,
	"GUM" : Guam,
	"GUY" : Guyana,
	"HKG" : HongKong,
	"HMD" : HeardIsland,
	"HND" : Honduras,
	"HRV" : Croatia,
	"HTI" : Haiti,
	"HUN" : Hungary,
	"IDN" : Indonesia,
	"IMN" : IsleOfMan,
	"IND" : India,
	"IOT" : BritishIndianOcean,
	"IRL" : Ireland,
	"IRN" : Iran,
	"IRQ" : Iraq,
	"ISL" : Iceland,
	"ISR" : Israel,
	"ITA" : Italy,
	"JAM" : Jamaica,
	"JEY" : Jersey,
	"JOR" : Jordan,
	"JPN" : Japan,
	"KAZ" : Kazakhstan,
	"KEN" : Kenya,
	"KGZ" : Kyrgyzstan,
	"KHM" : Cambodia,
	"KIR" : Kiribati,
	"KNA" : SaintKittsAndNevis,
	"KOR" : SouthKorea,
	"KWT" : Kuwait,
	"LAO" : Laos,
	"LBN" : Lebanon,
	"LBR" : Liberia,
	"LBY" : Libya,
	"LCA" : SaintLucia,
	"LIE" : Liechtenstein,
	"LKA" : SriLanka,
	"LSO" : Lesotho,
	"LTU" : Lithuania,
	"LUX" : Luxembourg,
	"LVA" : Latvia,
	"MAC" : Macao,
	"MAF" : SaintMartin,
	"MAR" : Morocco,
	"MCO" : Monaco,
	"MDA" : Moldova,
	"MDG" : Madagascar,
	"MDV" : Maldives,
	"MEX" : Mexico,
	"MHL" : MarshallIslands,
	"MKD" : NorthMacedonia,
	"MLI" : Mali,
	"MLT" : Malta,
	"MMR" : Myanmar,
	"MNE" : Montenegro,
	"MNG" : Mongolia,
	"MNP" : NorthernMarianaIslands,
	"MOZ" : Mozambique,
	"MRT" : Mauritania,
	"MSR" : Montserrat,
	"MTQ" : Martinique,
	"MUS" : Mauritius,
	"MWI" : Malawi,
	"MYS" : Malaysia,
	"MYT" : Mayotte,
	"NAM" : Namibia,
	"NCL" : NewCaledonia,
	"NER" : Niger,
	"NFK" : NorfolkIsland,
	"NGA" : Nigeria,
	"NIC" : Nicaragua,
	"NIU" : Niue,
	"NLD" : Netherlands,
	"NOR" : Norway,
	"NPL" : Nepal,
	"NRU" : Nauru,
	"NZL" : NewZealand,
	"OMN" : Oman,
	"PAK" : Pakistan,
	"PAN" : Panama,
	"PCN" : Pitcairn,
	"PER" : Peru,
	"PHL" : Philippines,
	"PLW" : Palau,
	"PNG" : PapuaNewGuinea,
	"POL" : Poland,
	"PRI" : PuertoRico,
	"PRK" : NorthKorea,
	"PRT" : Portugal,
	"PRY" : Paraguay,
	"PSE" : Palestine,
	"PYF" : FrenchPolynesia,
	"QAT" : Qatar,
	"REU" : Reunion,
	"ROU" : Romania,
	"RUS" : RussianFederation,
	"RWA" : Rwanda,
	"SAU" : SaudiArabia,
	"SDN" : Sudan,
	"SEN" : Senegal,
	"SGP" : Singapore,
	"SGS" : SouthGeorgia,
	"SHN" : SaintHelena,
	"SJM" : SvalbardAndJanMayen,
	"SLB" : SolomonIslands,
	"SLE" : SierraLeone,
	"SLV" : ElSalvador,
	"SMR" : SanMarino,
	"SOM" : Somalia,
	"SPM" : SaintPierreAndMiquelon,
	"SRB" : Serbia,
	"SSD" : SouthSudan,
	"STP" : SaoTomeAndPrincipe,
	"SUR" : Suriname,
	"SVK" : Slovakia,
	"SVN" : Slovenia,
	"SWE" : Sweden,
	"SWZ" : Eswatini,
	"SXM" : SintMaarten,
	"SYC" : Seychelles,
	"SYR" : Syria,
	"TCA" : TurksAndCaicosIslands,
	"TCD" : Chad,
	"TGO" : Togo,
	"THA" : Thailand,
	"TJK" : Tajikistan,
	"TKL" : Tokelau,
	"TKM" : Turkmenistan,
	"TLS" : TimorLeste,
	"TON" : Tonga,
	"TTO" : TrinidadAndTobago,
	"TUN" : Tunisia,
	"TUR" : Turkiye,
	"TUV" : Tuvalu,
	"TWN" : Taiwan,
	"TZA" : Tanzania,
	"UGA" : Uganda,
	"UKR" : Ukraine,
	"UMI" : USMinorOutlyingIslands,
	"URY" : Uruguay,
	"USA" : UnitedStates,
	"UZB" : Uzbekistan,
	"VAT" : Vatican,
	"VCT" : SaintVincentAndTheGrenadines,
	"VEN" : Venezuela,
	"VGB" : BritishVirginIslands,
	"VIR" : USVirginIslands,
	"VNM" : VietNam,
	"VUT" : Vanuatu,
	"WLF" : WallisAndFutuna,
	"WSM" : Samoa,
	"YEM" : Yemen,
	"ZAF" : SouthAfrica,
	"ZMB" : Zambia,
	"ZWE" : Zimbabwe,
}
