// Code generated by country/.generator; DO NOT EDIT.

package country

var (
	Andorra = Country{
		name:   "Andorra",
		alpha2: "AD",
		alpha3: "AND",
	}
	UnitedArabEmirates = Country{
		name:   "United Arab Emirates",
		alpha2: "AE",
		alpha3: "ARE",
	}
	Afghanistan = Country{
		name:   "Afghanistan",
		alpha2: "AF",
		alpha3: "AFG",
	}
	AntiguaAndBarbuda = Country{
		name:   "Antigua and Barbuda",
		alpha2: "AG",
		alpha3: "ATG",
	}
	Anguilla = Country{
		name:   "Anguilla",
		alpha2: "AI",
		alpha3: "AIA",
	}
	Albania = Country{
		name:   "Albania",
		alpha2: "AL",
		alpha3: "ALB",
	}
	Armenia = Country{
		name:   "Armenia",
		alpha2: "AM",
		alpha3: "ARM",
	}
	Angola = Country{
		name:   "Angola",
		alpha2: "AO",
		alpha3: "AGO",
	}
	Antarctica = Country{
		name:   "Antarctica",
		alpha2: "AQ",
		alpha3: "ATA",
	}
	Argentina = Country{
		name:   "Argentina",
		alpha2: "AR",
		alpha3: "ARG",
	}
	AmericanSamoa = Country{
		name:   "American Samoa",
		alpha2: "AS",
		alpha3: "ASM",
	}
	Austria = Country{
		name:   "Austria",
		alpha2: "AT",
		alpha3: "AUT",
	}
	Australia = Country{
		name:   "Australia",
		alpha2: "AU",
		alpha3: "AUS",
	}
	Aruba = Country{
		name:   "Aruba",
		alpha2: "AW",
		alpha3: "ABW",
	}
	AlandIslands = Country{
		name:   "Åland Islands",
		alpha2: "AX",
		alpha3: "ALA",
	}
	Azerbaijan = Country{
		name:   "Azerbaijan",
		alpha2: "AZ",
		alpha3: "AZE",
	}
	BosniaAndHerzegovina = Country{
		name:   "Bosnia and Herzegovina",
		alpha2: "BA",
		alpha3: "BIH",
	}
	Barbados = Country{
		name:   "Barbados",
		alpha2: "BB",
		alpha3: "BRB",
	}
	Bangladesh = Country{
		name:   "Bangladesh",
		alpha2: "BD",
		alpha3: "BGD",
	}
	Belgium = Country{
		name:   "Belgium",
		alpha2: "BE",
		alpha3: "BEL",
	}
	BurkinaFaso = Country{
		name:   "Burkina Faso",
		alpha2: "BF",
		alpha3: "BFA",
	}
	Bulgaria = Country{
		name:   "Bulgaria",
		alpha2: "BG",
		alpha3: "BGR",
	}
	Bahrain = Country{
		name:   "Bahrain",
		alpha2: "BH",
		alpha3: "BHR",
	}
	Burundi = Country{
		name:   "Burundi",
		alpha2: "BI",
		alpha3: "BDI",
	}
	Benin = Country{
		name:   "Benin",
		alpha2: "BJ",
		alpha3: "BEN",
	}
	SaintBarthelemy = Country{
		name:   "Saint Barthélemy",
		alpha2: "BL",
		alpha3: "BLM",
	}
	Bermuda = Country{
		name:   "Bermuda",
		alpha2: "BM",
		alpha3: "BMU",
	}
	BruneiDarussalam = Country{
		name:   "Brunei Darussalam",
		alpha2: "BN",
		alpha3: "BRN",
	}
	Bolivia = Country{
		name:   "Bolivia, Plurinational State of",
		alpha2: "BO",
		alpha3: "BOL",
	}
	Bonaire = Country{
		name:   "Bonaire, Sint Eustatius and Saba",
		alpha2: "BQ",
		alpha3: "BES",
	}
	Brazil = Country{
		name:   "Brazil",
		alpha2: "BR",
		alpha3: "BRA",
	}
	Bahamas = Country{
		name:   "Bahamas",
		alpha2: "BS",
		alpha3: "BHS",
	}
	Bhutan = Country{
		name:   "Bhutan",
		alpha2: "BT",
		alpha3: "BTN",
	}
	BouvetIsland = Country{
		name:   "Bouvet Island",
		alpha2: "BV",
		alpha3: "BVT",
	}
	Botswana = Country{
		name:   "Botswana",
		alpha2: "BW",
		alpha3: "BWA",
	}
	Belarus = Country{
		name:   "Belarus",
		alpha2: "BY",
		alpha3: "BLR",
	}
	Belize = Country{
		name:   "Belize",
		alpha2: "BZ",
		alpha3: "BLZ",
	}
	Canada = Country{
		name:   "Canada",
		alpha2: "CA",
		alpha3: "CAN",
	}
	CocosIslands = Country{
		name:   "Cocos (Keeling) Islands",
		alpha2: "CC",
		alpha3: "CCK",
	}
	DRCongo = Country{
		name:   "Congo, The Democratic Republic of the",
		alpha2: "CD",
		alpha3: "COD",
	}
	CentralAfricanRepublic = Country{
		name:   "Central African Republic",
		alpha2: "CF",
		alpha3: "CAF",
	}
	Congo = Country{
		name:   "Congo",
		alpha2: "CG",
		alpha3: "COG",
	}
	Switzerland = Country{
		name:   "Switzerland",
		alpha2: "CH",
		alpha3: "CHE",
	}
	CoteDIvoire = Country{
		name:   "Côte d'Ivoire",
		alpha2: "CI",
		alpha3: "CIV",
	}
	CookIslands = Country{
		name:   "Cook Islands",
		alpha2: "CK",
		alpha3: "COK",
	}
	Chile = Country{
		name:   "Chile",
		alpha2: "CL",
		alpha3: "CHL",
	}
	Cameroon = Country{
		name:   "Cameroon",
		alpha2: "CM",
		alpha3: "CMR",
	}
	China = Country{
		name:   "China",
		alpha2: "CN",
		alpha3: "CHN",
	}
	Colombia = Country{
		name:   "Colombia",
		alpha2: "CO",
		alpha3: "COL",
	}
	CostaRica = Country{
		name:   "Costa Rica",
		alpha2: "CR",
		alpha3: "CRI",
	}
	Cuba = Country{
		name:   "Cuba",
		alpha2: "CU",
		alpha3: "CUB",
	}
	CaboVerde = Country{
		name:   "Cabo Verde",
		alpha2: "CV",
		alpha3: "CPV",
	}
	Curacao = Country{
		name:   "Curaçao",
		alpha2: "CW",
		alpha3: "CUW",
	}
	ChristmasIsland = Country{
		name:   "Christmas Island",
		alpha2: "CX",
		alpha3: "CXR",
	}
	Cyprus = Country{
		name:   "Cyprus",
		alpha2: "CY",
		alpha3: "CYP",
	}
	Czechia = Country{
		name:   "Czechia",
		alpha2: "CZ",
		alpha3: "CZE",
	}
	Germany = Country{
		name:   "Germany",
		alpha2: "DE",
		alpha3: "DEU",
	}
	Djibouti = Country{
		name:   "Djibouti",
		alpha2: "DJ",
		alpha3: "DJI",
	}
	Denmark = Country{
		name:   "Denmark",
		alpha2: "DK",
		alpha3: "DNK",
	}
	Dominica = Country{
		name:   "Dominica",
		alpha2: "DM",
		alpha3: "DMA",
	}
	DominicanRepublic = Country{
		name:   "Dominican Republic",
		alpha2: "DO",
		alpha3: "DOM",
	}
	Algeria = Country{
		name:   "Algeria",
		alpha2: "DZ",
		alpha3: "DZA",
	}
	Ecuador = Country{
		name:   "Ecuador",
		alpha2: "EC",
		alpha3: "ECU",
	}
	Estonia = Country{
		name:   "Estonia",
		alpha2: "EE",
		alpha3: "EST",
	}
	Egypt = Country{
		name:   "Egypt",
		alpha2: "EG",
		alpha3: "EGY",
	}
	WesternSahara = Country{
		name:   "Western Sahara",
		alpha2: "EH",
		alpha3: "ESH",
	}
	Eritrea = Country{
		name:   "Eritrea",
		alpha2: "ER",
		alpha3: "ERI",
	}
	Spain = Country{
		name:   "Spain",
		alpha2: "ES",
		alpha3: "ESP",
	}
	Ethiopia = Country{
		name:   "Ethiopia",
		alpha2: "ET",
		alpha3: "ETH",
	}
	Finland = Country{
		name:   "Finland",
		alpha2: "FI",
		alpha3: "FIN",
	}
	Fiji = Country{
		name:   "Fiji",
		alpha2: "FJ",
		alpha3: "FJI",
	}
	FalklandIslands = Country{
		name:   "Falkland Islands (Malvinas)",
		alpha2: "FK",
		alpha3: "FLK",
	}
	Micronesia = Country{
		name:   "Micronesia, Federated States of",
		alpha2: "FM",
		alpha3: "FSM",
	}
	FaroeIslands = Country{
		name:   "Faroe Islands",
		alpha2: "FO",
		alpha3: "FRO",
	}
	France = Country{
		name:   "France",
		alpha2: "FR",
		alpha3: "FRA",
	}
	Gabon = Country{
		name:   "Gabon",
		alpha2: "GA",
		alpha3: "GAB",
	}
	UnitedKingdom = Country{
		name:   "United Kingdom",
		alpha2: "GB",
		alpha3: "GBR",
	}
	Grenada = Country{
		name:   "Grenada",
		alpha2: "GD",
		alpha3: "GRD",
	}
	Georgia = Country{
		name:   "Georgia",
		alpha2: "GE",
		alpha3: "GEO",
	}
	FrenchGuiana = Country{
		name:   "French Guiana",
		alpha2: "GF",
		alpha3: "GUF",
	}
	Guernsey = Country{
		name:   "Guernsey",
		alpha2: "GG",
		alpha3: "GGY",
	}
	Ghana = Country{
		name:   "Ghana",
		alpha2: "GH",
		alpha3: "GHA",
	}
	Gibraltar = Country{
		name:   "Gibraltar",
		alpha2: "GI",
		alpha3: "GIB",
	}
	Greenland = Country{
		name:   "Greenland",
		alpha2: "GL",
		alpha3: "GRL",
	}
	Gambia = Country{
		name:   "Gambia",
		alpha2: "GM",
		alpha3: "GMB",
	}
	Guinea = Country{
		name:   "Guinea",
		alpha2: "GN",
		alpha3: "GIN",
	}
	Guadeloupe = Country{
		name:   "Guadeloupe",
		alpha2: "GP",
		alpha3: "GLP",
	}
	EquatorialGuinea = Country{
		name:   "Equatorial Guinea",
		alpha2: "GQ",
		alpha3: "GNQ",
	}
	Greece = Country{
		name:   "Greece",
		alpha2: "GR",
		alpha3: "GRC",
	}
	SouthGeorgia = Country{
		name:   "South Georgia and the South Sandwich Islands",
		alpha2: "GS",
		alpha3: "SGS",
	}
	Guatemala = Country{
		name:   "Guatemala",
		alpha2: "GT",
		alpha3: "GTM",
	}
	Guam = Country{
		name:   "Guam",
		alpha2: "GU",
		alpha3: "GUM",
	}
	GuineaBissau = Country{
		name:   "Guinea-Bissau",
		alpha2: "GW",
		alpha3: "GNB",
	}
	Guyana = Country{
		name:   "Guyana",
		alpha2: "GY",
		alpha3: "GUY",
	}
	HongKong = Country{
		name:   "Hong Kong",
		alpha2: "HK",
		alpha3: "HKG",
	}
	HeardIsland = Country{
		name:   "Heard Island and McDonald Islands",
		alpha2: "HM",
		alpha3: "HMD",
	}
	Honduras = Country{
		name:   "Honduras",
		alpha2: "HN",
		alpha3: "HND",
	}
	Croatia = Country{
		name:   "Croatia",
		alpha2: "HR",
		alpha3: "HRV",
	}
	Haiti = Country{
		name:   "Haiti",
		alpha2: "HT",
		alpha3: "HTI",
	}
	Hungary = Country{
		name:   "Hungary",
		alpha2: "HU",
		alpha3: "HUN",
	}
	Indonesia = Country{
		name:   "Indonesia",
		alpha2: "ID",
		alpha3: "IDN",
	}
	Ireland = Country{
		name:   "Ireland",
		alpha2: "IE",
		alpha3: "IRL",
	}
	Israel = Country{
		name:   "Israel",
		alpha2: "IL",
		alpha3: "ISR",
	}
	IsleOfMan = Country{
		name:   "Isle of Man",
		alpha2: "IM",
		alpha3: "IMN",
	}
	India = Country{
		name:   "India",
		alpha2: "IN",
		alpha3: "IND",
	}
	BritishIndianOcean = Country{
		name:   "British Indian Ocean Territory",
		alpha2: "IO",
		alpha3: "IOT",
	}
	Iraq = Country{
		name:   "Iraq",
		alpha2: "IQ",
		alpha3: "IRQ",
	}
	Iran = Country{
		name:   "Iran, Islamic Republic of",
		alpha2: "IR",
		alpha3: "IRN",
	}
	Iceland = Country{
		name:   "Iceland",
		alpha2: "IS",
		alpha3: "ISL",
	}
	Italy = Country{
		name:   "Italy",
		alpha2: "IT",
		alpha3: "ITA",
	}
	Jersey = Country{
		name:   "Jersey",
		alpha2: "JE",
		alpha3: "JEY",
	}
	Jamaica = Country{
		name:   "Jamaica",
		alpha2: "JM",
		alpha3: "JAM",
	}
	Jordan = Country{
		name:   "Jordan",
		alpha2: "JO",
		alpha3: "JOR",
	}
	Japan = Country{
		name:   "Japan",
		alpha2: "JP",
		alpha3: "JPN",
	}
	Kenya = Country{
		name:   "Kenya",
		alpha2: "KE",
		alpha3: "KEN",
	}
	Kyrgyzstan = Country{
		name:   "Kyrgyzstan",
		alpha2: "KG",
		alpha3: "KGZ",
	}
	Cambodia = Country{
		name:   "Cambodia",
		alpha2: "KH",
		alpha3: "KHM",
	}
	Kiribati = Country{
		name:   "Kiribati",
		alpha2: "KI",
		alpha3: "KIR",
	}
	Comoros = Country{
		name:   "Comoros",
		alpha2: "KM",
		alpha3: "COM",
	}
	SaintKittsAndNevis = Country{
		name:   "Saint Kitts and Nevis",
		alpha2: "KN",
		alpha3: "KNA",
	}
	NorthKorea = Country{
		name:   "Korea, Democratic People's Republic of",
		alpha2: "KP",
		alpha3: "PRK",
	}
	SouthKorea = Country{
		name:   "Korea, Republic of",
		alpha2: "KR",
		alpha3: "KOR",
	}
	Kuwait = Country{
		name:   "Kuwait",
		alpha2: "KW",
		alpha3: "KWT",
	}
	CaymanIslands = Country{
		name:   "Cayman Islands",
		alpha2: "KY",
		alpha3: "CYM",
	}
	Kazakhstan = Country{
		name:   "Kazakhstan",
		alpha2: "KZ",
		alpha3: "KAZ",
	}
	Laos = Country{
		name:   "Lao People's Democratic Republic",
		alpha2: "LA",
		alpha3: "LAO",
	}
	Lebanon = Country{
		name:   "Lebanon",
		alpha2: "LB",
		alpha3: "LBN",
	}
	SaintLucia = Country{
		name:   "Saint Lucia",
		alpha2: "LC",
		alpha3: "LCA",
	}
	Liechtenstein = Country{
		name:   "Liechtenstein",
		alpha2: "LI",
		alpha3: "LIE",
	}
	SriLanka = Country{
		name:   "Sri Lanka",
		alpha2: "LK",
		alpha3: "LKA",
	}
	Liberia = Country{
		name:   "Liberia",
		alpha2: "LR",
		alpha3: "LBR",
	}
	Lesotho = Country{
		name:   "Lesotho",
		alpha2: "LS",
		alpha3: "LSO",
	}
	Lithuania = Country{
		name:   "Lithuania",
		alpha2: "LT",
		alpha3: "LTU",
	}
	Luxembourg = Country{
		name:   "Luxembourg",
		alpha2: "LU",
		alpha3: "LUX",
	}
	Latvia = Country{
		name:   "Latvia",
		alpha2: "LV",
		alpha3: "LVA",
	}
	Libya = Country{
		name:   "Libya",
		alpha2: "LY",
		alpha3: "LBY",
	}
	Morocco = Country{
		name:   "Morocco",
		alpha2: "MA",
		alpha3: "MAR",
	}
	Monaco = Country{
		name:   "Monaco",
		alpha2: "MC",
		alpha3: "MCO",
	}
	Moldova = Country{
		name:   "Moldova, Republic of",
		alpha2: "MD",
		alpha3: "MDA",
	}
	Montenegro = Country{
		name:   "Montenegro",
		alpha2: "ME",
		alpha3: "MNE",
	}
	SaintMartin = Country{
		name:   "Saint Martin (French part)",
		alpha2: "MF",
		alpha3: "MAF",
	}
	Madagascar = Country{
		name:   "Madagascar",
		alpha2: "MG",
		alpha3: "MDG",
	}
	MarshallIslands = Country{
		name:   "Marshall Islands",
		alpha2: "MH",
		alpha3: "MHL",
	}
	NorthMacedonia = Country{
		name:   "North Macedonia",
		alpha2: "MK",
		alpha3: "MKD",
	}
	Mali = Country{
		name:   "Mali",
		alpha2: "ML",
		alpha3: "MLI",
	}
	Myanmar = Country{
		name:   "Myanmar",
		alpha2: "MM",
		alpha3: "MMR",
	}
	Mongolia = Country{
		name:   "Mongolia",
		alpha2: "MN",
		alpha3: "MNG",
	}
	Macao = Country{
		name:   "Macao",
		alpha2: "MO",
		alpha3: "MAC",
	}
	NorthernMarianaIslands = Country{
		name:   "Northern Mariana Islands",
		alpha2: "MP",
		alpha3: "MNP",
	}
	Martinique = Country{
		name:   "Martinique",
		alpha2: "MQ",
		alpha3: "MTQ",
	}
	Mauritania = Country{
		name:   "Mauritania",
		alpha2: "MR",
		alpha3: "MRT",
	}
	Montserrat = Country{
		name:   "Montserrat",
		alpha2: "MS",
		alpha3: "MSR",
	}
	Malta = Country{
		name:   "Malta",
		alpha2: "MT",
		alpha3: "MLT",
	}
	Mauritius = Country{
		name:   "Mauritius",
		alpha2: "MU",
		alpha3: "MUS",
	}
	Maldives = Country{
		name:   "Maldives",
		alpha2: "MV",
		alpha3: "MDV",
	}
	Malawi = Country{
		name:   "Malawi",
		alpha2: "MW",
		alpha3: "MWI",
	}
	Mexico = Country{
		name:   "Mexico",
		alpha2: "MX",
		alpha3: "MEX",
	}
	Malaysia = Country{
		name:   "Malaysia",
		alpha2: "MY",
		alpha3: "MYS",
	}
	Mozambique = Country{
		name:   "Mozambique",
		alpha2: "MZ",
		alpha3: "MOZ",
	}
	Namibia = Country{
		name:   "Namibia",
		alpha2: "NA",
		alpha3: "NAM",
	}
	NewCaledonia = Country{
		name:   "New Caledonia",
		alpha2: "NC",
		alpha3: "NCL",
	}
	Niger = Country{
		name:   "Niger",
		alpha2: "NE",
		alpha3: "NER",
	}
	NorfolkIsland = Country{
		name:   "Norfolk Island",
		alpha2: "NF",
		alpha3: "NFK",
	}
	Nigeria = Country{
		name:   "Nigeria",
		alpha2: "NG",
		alpha3: "NGA",
	}
	Nicaragua = Country{
		name:   "Nicaragua",
		alpha2: "NI",
		alpha3: "NIC",
	}
	Netherlands = Country{
		name:   "Netherlands",
		alpha2: "NL",
		alpha3: "NLD",
	}
	Norway = Country{
		name:   "Norway",
		alpha2: "NO",
		alpha3: "NOR",
	}
	Nepal = Country{
		name:   "Nepal",
		alpha2: "NP",
		alpha3: "NPL",
	}
	Nauru = Country{
		name:   "Nauru",
		alpha2: "NR",
		alpha3: "NRU",
	}
	Niue = Country{
		name:   "Niue",
		alpha2: "NU",
		alpha3: "NIU",
	}
	NewZealand = Country{
		name:   "New Zealand",
		alpha2: "NZ",
		alpha3: "NZL",
	}
	Oman = Country{
		name:   "Oman",
		alpha2: "OM",
		alpha3: "OMN",
	}
	Panama = Country{
		name:   "Panama",
		alpha2: "PA",
		alpha3: "PAN",
	}
	Peru = Country{
		name:   "Peru",
		alpha2: "PE",
		alpha3: "PER",
	}
	FrenchPolynesia = Country{
		name:   "French Polynesia",
		alpha2: "PF",
		alpha3: "PYF",
	}
	PapuaNewGuinea = Country{
		name:   "Papua New Guinea",
		alpha2: "PG",
		alpha3: "PNG",
	}
	Philippines = Country{
		name:   "Philippines",
		alpha2: "PH",
		alpha3: "PHL",
	}
	Pakistan = Country{
		name:   "Pakistan",
		alpha2: "PK",
		alpha3: "PAK",
	}
	Poland = Country{
		name:   "Poland",
		alpha2: "PL",
		alpha3: "POL",
	}
	SaintPierreAndMiquelon = Country{
		name:   "Saint Pierre and Miquelon",
		alpha2: "PM",
		alpha3: "SPM",
	}
	Pitcairn = Country{
		name:   "Pitcairn",
		alpha2: "PN",
		alpha3: "PCN",
	}
	PuertoRico = Country{
		name:   "Puerto Rico",
		alpha2: "PR",
		alpha3: "PRI",
	}
	Palestine = Country{
		name:   "Palestine, State of",
		alpha2: "PS",
		alpha3: "PSE",
	}
	Portugal = Country{
		name:   "Portugal",
		alpha2: "PT",
		alpha3: "PRT",
	}
	Palau = Country{
		name:   "Palau",
		alpha2: "PW",
		alpha3: "PLW",
	}
	Paraguay = Country{
		name:   "Paraguay",
		alpha2: "PY",
		alpha3: "PRY",
	}
	Qatar = Country{
		name:   "Qatar",
		alpha2: "QA",
		alpha3: "QAT",
	}
	Reunion = Country{
		name:   "Réunion",
		alpha2: "RE",
		alpha3: "REU",
	}
	Romania = Country{
		name:   "Romania",
		alpha2: "RO",
		alpha3: "ROU",
	}
	Serbia = Country{
		name:   "Serbia",
		alpha2: "RS",
		alpha3: "SRB",
	}
	RussianFederation = Country{
		name:   "Russian Federation",
		alpha2: "RU",
		alpha3: "RUS",
	}
	Rwanda = Country{
		name:   "Rwanda",
		alpha2: "RW",
		alpha3: "RWA",
	}
	SaudiArabia = Country{
		name:   "Saudi Arabia",
		alpha2: "SA",
		alpha3: "SAU",
	}
	SolomonIslands = Country{
		name:   "Solomon Islands",
		alpha2: "SB",
		alpha3: "SLB",
	}
	Seychelles = Country{
		name:   "Seychelles",
		alpha2: "SC",
		alpha3: "SYC",
	}
	Sudan = Country{
		name:   "Sudan",
		alpha2: "SD",
		alpha3: "SDN",
	}
	Sweden = Country{
		name:   "Sweden",
		alpha2: "SE",
		alpha3: "SWE",
	}
	Singapore = Country{
		name:   "Singapore",
		alpha2: "SG",
		alpha3: "SGP",
	}
	SaintHelena = Country{
		name:   "Saint Helena, Ascension and Tristan da Cunha",
		alpha2: "SH",
		alpha3: "SHN",
	}
	Slovenia = Country{
		name:   "Slovenia",
		alpha2: "SI",
		alpha3: "SVN",
	}
	SvalbardAndJanMayen = Country{
		name:   "Svalbard and Jan Mayen",
		alpha2: "SJ",
		alpha3: "SJM",
	}
	Slovakia = Country{
		name:   "Slovakia",
		alpha2: "SK",
		alpha3: "SVK",
	}
	SierraLeone = Country{
		name:   "Sierra Leone",
		alpha2: "SL",
		alpha3: "SLE",
	}
	SanMarino = Country{
		name:   "San Marino",
		alpha2: "SM",
		alpha3: "SMR",
	}
	Senegal = Country{
		name:   "Senegal",
		alpha2: "SN",
		alpha3: "SEN",
	}
	Somalia = Country{
		name:   "Somalia",
		alpha2: "SO",
		alpha3: "SOM",
	}
	Suriname = Country{
		name:   "Suriname",
		alpha2: "SR",
		alpha3: "SUR",
	}
	SouthSudan = Country{
		name:   "South Sudan",
		alpha2: "SS",
		alpha3: "SSD",
	}
	SaoTomeAndPrincipe = Country{
		name:   "Sao Tome and Principe",
		alpha2: "ST",
		alpha3: "STP",
	}
	ElSalvador = Country{
		name:   "El Salvador",
		alpha2: "SV",
		alpha3: "SLV",
	}
	SintMaarten = Country{
		name:   "Sint Maarten (Dutch part)",
		alpha2: "SX",
		alpha3: "SXM",
	}
	Syria = Country{
		name:   "Syrian Arab Republic",
		alpha2: "SY",
		alpha3: "SYR",
	}
	Eswatini = Country{
		name:   "Eswatini",
		alpha2: "SZ",
		alpha3: "SWZ",
	}
	TurksAndCaicosIslands = Country{
		name:   "Turks and Caicos Islands",
		alpha2: "TC",
		alpha3: "TCA",
	}
	Chad = Country{
		name:   "Chad",
		alpha2: "TD",
		alpha3: "TCD",
	}
	FrenchSouthern = Country{
		name:   "French Southern Territories",
		alpha2: "TF",
		alpha3: "ATF",
	}
	Togo = Country{
		name:   "Togo",
		alpha2: "TG",
		alpha3: "TGO",
	}
	Thailand = Country{
		name:   "Thailand",
		alpha2: "TH",
		alpha3: "THA",
	}
	Tajikistan = Country{
		name:   "Tajikistan",
		alpha2: "TJ",
		alpha3: "TJK",
	}
	Tokelau = Country{
		name:   "Tokelau",
		alpha2: "TK",
		alpha3: "TKL",
	}
	TimorLeste = Country{
		name:   "Timor-Leste",
		alpha2: "TL",
		alpha3: "TLS",
	}
	Turkmenistan = Country{
		name:   "Turkmenistan",
		alpha2: "TM",
		alpha3: "TKM",
	}
	Tunisia = Country{
		name:   "Tunisia",
		alpha2: "TN",
		alpha3: "TUN",
	}
	Tonga = Country{
		name:   "Tonga",
		alpha2: "TO",
		alpha3: "TON",
	}
	Turkiye = Country{
		name:   "Türkiye",
		alpha2: "TR",
		alpha3: "TUR",
	}
	TrinidadAndTobago = Country{
		name:   "Trinidad and Tobago",
		alpha2: "TT",
		alpha3: "TTO",
	}
	Tuvalu = Country{
		name:   "Tuvalu",
		alpha2: "TV",
		alpha3: "TUV",
	}
	Taiwan = Country{
		name:   "Taiwan, Province of China",
		alpha2: "TW",
		alpha3: "TWN",
	}
	Tanzania = Country{
		name:   "Tanzania, United Republic of",
		alpha2: "TZ",
		alpha3: "TZA",
	}
	Ukraine = Country{
		name:   "Ukraine",
		alpha2: "UA",
		alpha3: "UKR",
	}
	Uganda = Country{
		name:   "Uganda",
		alpha2: "UG",
		alpha3: "UGA",
	}
	USMinorOutlyingIslands = Country{
		name:   "United States Minor Outlying Islands",
		alpha2: "UM",
		alpha3: "UMI",
	}
	UnitedStates = Country{
		name:   "United States",
		alpha2: "US",
		alpha3: "USA",
	}
	Uruguay = Country{
		name:   "Uruguay",
		alpha2: "UY",
		alpha3: "URY",
	}
	Uzbekistan = Country{
		name:   "Uzbekistan",
		alpha2: "UZ",
		alpha3: "UZB",
	}
	Vatican = Country{
		name:   "Holy See (Vatican City State)",
		alpha2: "VA",
		alpha3: "VAT",
	}
	SaintVincentAndTheGrenadines = Country{
		name:   "Saint Vincent and the Grenadines",
		alpha2: "VC",
		alpha3: "VCT",
	}
	Venezuela = Country{
		name:   "Venezuela, Bolivarian Republic of",
		alpha2: "VE",
		alpha3: "VEN",
	}
	BritishVirginIslands = Country{
		name:   "Virgin Islands, British",
		alpha2: "VG",
		alpha3: "VGB",
	}
	USVirginIslands = Country{
		name:   "Virgin Islands, U.S.",
		alpha2: "VI",
		alpha3: "VIR",
	}
	VietNam = Country{
		name:   "Viet Nam",
		alpha2: "VN",
		alpha3: "VNM",
	}
	Vanuatu = Country{
		name:   "Vanuatu",
		alpha2: "VU",
		alpha3: "VUT",
	}
	WallisAndFutuna = Country{
		name:   "Wallis and Futuna",
		alpha2: "WF",
		alpha3: "WLF",
	}
	Samoa = Country{
		name:   "Samoa",
		alpha2: "WS",
		alpha3: "WSM",
	}
	Yemen = Country{
		name:   "Yemen",
		alpha2: "YE",
		alpha3: "YEM",
	}
	Mayotte = Country{
		name:   "Mayotte",
		alpha2: "YT",
		alpha3: "MYT",
	}
	SouthAfrica = Country{
		name:   "South Africa",
		alpha2: "ZA",
		alpha3: "ZAF",
	}
	Zambia = Country{
		name:   "Zambia",
		alpha2: "ZM",
		alpha3: "ZMB",
	}
	Zimbabwe = Country{
		name:   "Zimbabwe",
		alpha2: "ZW",
		alpha3: "ZWE",
	}
)
